//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeafWeb.LeafService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecognizedLeaf", Namespace="http://schemas.datacontract.org/2004/07/LeafService")]
    [System.SerializableAttribute()]
    public partial class RecognizedLeaf : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ConfidencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LatinNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Confidency {
            get {
                return this.ConfidencyField;
            }
            set {
                if ((this.ConfidencyField.Equals(value) != true)) {
                    this.ConfidencyField = value;
                    this.RaisePropertyChanged("Confidency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LatinName {
            get {
                return this.LatinNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LatinNameField, value) != true)) {
                    this.LatinNameField = value;
                    this.RaisePropertyChanged("LatinName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Descriptor", Namespace="http://schemas.datacontract.org/2004/07/LeafService")]
    [System.SerializableAttribute()]
    public partial class Descriptor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SenderInfo", Namespace="http://schemas.datacontract.org/2004/07/LeafService")]
    [System.SerializableAttribute()]
    public partial class SenderInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LeafService.ILeafService")]
    public interface ILeafService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeafService/SayHello", ReplyAction="http://tempuri.org/ILeafService/SayHelloResponse")]
        string SayHello();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeafService/Recognize", ReplyAction="http://tempuri.org/ILeafService/RecognizeResponse")]
        LeafWeb.LeafService.RecognizedLeaf[] Recognize(string picture, int noAnswers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeafService/Learn", ReplyAction="http://tempuri.org/ILeafService/LearnResponse")]
        bool Learn(LeafWeb.LeafService.Descriptor[] descriptors, string picture, string treeName, LeafWeb.LeafService.SenderInfo senderInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILeafServiceChannel : LeafWeb.LeafService.ILeafService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LeafServiceClient : System.ServiceModel.ClientBase<LeafWeb.LeafService.ILeafService>, LeafWeb.LeafService.ILeafService {
        
        public LeafServiceClient() {
        }
        
        public LeafServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LeafServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeafServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeafServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SayHello() {
            return base.Channel.SayHello();
        }
        
        public LeafWeb.LeafService.RecognizedLeaf[] Recognize(string picture, int noAnswers) {
            return base.Channel.Recognize(picture, noAnswers);
        }
        
        public bool Learn(LeafWeb.LeafService.Descriptor[] descriptors, string picture, string treeName, LeafWeb.LeafService.SenderInfo senderInfo) {
            return base.Channel.Learn(descriptors, picture, treeName, senderInfo);
        }
    }
}
